import os
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from transformers import AutoModelForCausalLM, AutoTokenizer
import numpy as np
from tqdm import tqdm
from PIL import Image
from dataclasses import dataclass
from typing import List, Dict, Tuple, Optional, Union, Any
import secrets

# Set random seeds for reproducibility
def set_seed(seed: int = 42):
    secrets.SystemRandom().seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(42)
@dataclass
class TrajectoryStep:
    state_image: str  # Path to image file
    state_desc: str   # Text description of state
    action: str       # Action taken
    object: str       # Object acted upon
    reasoning: str    # Reasoning behind action
    success: bool     # Whether action execution succeeded
    
@dataclass
class Trajectory:
    goal: str
    steps: List[TrajectoryStep]
    success: bool  # Whether trajectory reached the goal
    
@dataclass
class ActionPreferencePair:
    goal: str
    prev_actions: List[str]
    prev_observations: List[str]
    chosen_reasoning: str
    chosen_action: str
    rejected_reasoning: str
    rejected_action: str
    
@dataclass
class StatePreferencePair:
    current_state_image: str
    current_state_desc: str
    action: str
    chosen_next_state: str
    rejected_next_state: str

#################################
# Tree Search for Data Collection
#################################

class TreeSearchNode:
    def __init__(self, state_image, state_desc, action=None, parent=None):
        self.state_image = state_image
        self.state_desc = state_desc
        self.action = action  # Action that led to this state
        self.parent = parent
        self.children = []
        self.score = 0.0
        
    def add_child(self, state_image, state_desc, action, score):
        child = TreeSearchNode(state_image, state_desc, action, self)
        child.score = score
        self.children.append(child)
        return child
    
    def get_path(self):
        """Get path from root to this node"""
        path = []
        current = self
        while current.parent is not None:
            path.append(current)
            current = current.parent
        path.append(current)  # Add root
        return list(reversed(path))

class TreeSearch:
    def __init__(self, env, policy_model, process_reward_model, threshold=3.75, alpha=0.5, max_depth=25, max_children=5):
        """
        Initialize the tree search
        
        Args:
            env: Environment simulator
            policy_model: Model for sampling actions
            process_reward_model: Model for evaluating actions (GPT-4o in the paper)
            threshold: Minimum score for action to be selected for expansion
            alpha: Weight for process reward vs environmental feasibility
            max_depth: Maximum tree depth
            max_children: Maximum number of children to explore per node
        """
        self.env = env
        self.policy_model = policy_model
        self.process_reward_model = process_reward_model
        self.threshold = threshold
        self.alpha = alpha
        self.max_depth = max_depth
        self.max_children = max_children
        
    def sample_actions(self, state_image, state_desc, goal, previous_actions, num_samples=5):
        """Sample potential actions from policy model"""
        # This would interface with your policy model to generate actions
        # For simplicity, we'll return dummy actions
        actions = [
            {"action": "find", "object": "cup", "reasoning": "Need to locate the cup first"},
            {"action": "pickup", "object": "cup", "reasoning": "Need to pick up the cup before using it"},
            # ... more actions would be generated by the model
        ]
        return actions[:num_samples]
    
    def evaluate_action(self, state_image, state_desc, goal, action, previous_actions):
        """Evaluate an action using both process reward and environmental feasibility"""
        # Process reward from GPT-4o (scale 0-5)
        proc_reward = self.process_reward_model.evaluate(
            state_image, state_desc, goal, action, previous_actions
        )
        
        # Environmental feasibility from simulator (0 or 1)
        env_feasibility = self.env.check_action_feasibility(state_image, action)
        
        # Combined score
        total_score = self.alpha * proc_reward + (1 - self.alpha) * env_feasibility
        
        return {
            "proc_reward": proc_reward,
            "env_feasibility": env_feasibility,
            "total_score": total_score
        }
    
    def execute_action(self, state_image, action):
        """Execute action in the environment and get next state"""
        success, next_state_image, next_state_desc = self.env.step(state_image, action)
        return success, next_state_image, next_state_desc
    
    def check_goal_reached(self, state_image, state_desc, goal):
        """Check if the goal has been reached"""
        return self.env.check_goal_completion(state_image, state_desc, goal)
    
    def search(self, initial_state_image, initial_state_desc, goal):
        """
        Perform tree search to find a successful trajectory
        
        Args:
            initial_state_image: Path to initial state image
            initial_state_desc: Description of initial state
            goal: Goal instruction
            
        Returns:
            List of successful trajectories
        """
        root = TreeSearchNode(initial_state_image, initial_state_desc)
        queue = [(root, 0)]  # (node, depth)
        successful_trajectories = []
        
        while queue:
            node, depth = queue.pop(0)
            
            # Check if we've reached max depth
            if depth >= self.max_depth:
                continue
                
            # Check if goal is reached
            if self.check_goal_reached(node.state_image, node.state_desc, goal):
                path = node.get_path()
                trajectory = self.construct_trajectory(path, goal)
                successful_trajectories.append(trajectory)
                continue
            
            # Get path so far for context
            path_so_far = node.get_path()
            previous_actions = [n.action for n in path_so_far if n.action is not None]
            
            # Sample potential actions
            potential_actions = self.sample_actions(
                node.state_image, 
                node.state_desc, 
                goal, 
                previous_actions,
                self.max_children
            )
            
            # Evaluate and filter actions
            for action_info in potential_actions:
                action = action_info["action"] + " " + action_info["object"]
                reasoning = action_info["reasoning"]
                
                # Evaluate action
                evaluation = self.evaluate_action(
                    node.state_image, 
                    node.state_desc, 
                    goal, 
                    action, 
                    previous_actions
                )
                
                # Only expand if score is above threshold
                if evaluation["total_score"] >= self.threshold:
                    # Execute action in the environment
                    success, next_state_image, next_state_desc = self.execute_action(
                        node.state_image, action
                    )
                    
                    if success:
                        # Create child node
                        action_with_reasoning = {
                            "action": action,
                            "reasoning": reasoning
                        }
                        child = node.add_child(
                            next_state_image, 
                            next_state_desc, 
                            action_with_reasoning,
                            evaluation["total_score"]
                        )
                        
                        # Add to queue for breadth-first exploration
                        queue.append((child, depth + 1))
        
        return successful_trajectories
    
    def construct_trajectory(self, path, goal):
        """Convert a path of nodes to a trajectory"""
        steps = []
        
        for i in range(1, len(path)):
            prev_node = path[i-1]
            node = path[i]
            
            action_info = node.action
            
            step = TrajectoryStep(
                state_image=prev_node.state_image,
                state_desc=prev_node.state_desc,
                action=action_info["action"].split()[0],
                object=action_info["action"].split()[1] if len(action_info["action"].split()) > 1 else "",
                reasoning=action_info["reasoning"],
                success=True  # Since these are steps from successful execution
            )
            steps.append(step)
        
        return Trajectory(goal=goal, steps=steps, success=True)

class PreferenceDataGenerator:
    def __init__(self, tree_search, gpt4o_state_describer):
        self.tree_search = tree_search
        self.gpt4o_state_describer = gpt4o_state_describer
        
    def generate_action_preference_pairs(self, successful_trajectory, all_sampled_actions):
        """
        Generate action preference pairs from a successful trajectory
        
        Args:
            successful_trajectory: A successful trajectory
            all_sampled_actions: Dictionary mapping (state_image, step) to all sampled actions at that step
            
        Returns:
            List of action preference pairs
        """
        pairs = []
        goal = successful_trajectory.goal
        
        for i, step in enumerate(successful_trajectory.steps):
            # Get history so far
            prev_steps = successful_trajectory.steps[:i]
            prev_actions = [s.action + " " + s.object for s in prev_steps]
            prev_observations = [s.state_desc for s in prev_steps]
            
            # Chosen action
            chosen_action = step.action + " " + step.object
            chosen_reasoning = step.reasoning
            
            # Get rejected actions for this state
            state_key = (step.state_image, i)
            if state_key in all_sampled_actions:
                rejected_actions = [
                    a for a in all_sampled_actions[state_key] 
                    if a["action"] + " " + a["object"] != chosen_action
                ]
                
                for rejected in rejected_actions:
                    rejected_action = rejected["action"] + " " + rejected["object"]
                    rejected_reasoning = rejected["reasoning"]
                    
                    pair = ActionPreferencePair(
                        goal=goal,
                        prev_actions=prev_actions,
                        prev_observations=prev_observations,
                        chosen_reasoning=chosen_reasoning,
                        chosen_action=chosen_action,
                        rejected_reasoning=rejected_reasoning,
                        rejected_action=rejected_action
                    )
                    pairs.append(pair)
        
        return pairs
    
    def generate_state_preference_pairs(self, successful_trajectory, all_executed_actions):
        """
        Generate state preference pairs from a successful trajectory
        
        Args:
            successful_trajectory: A successful trajectory
            all_executed_actions: Dictionary mapping (state_image, action) to 
                                 outcomes of all executed actions
            
        Returns:
            List of state preference pairs
        """
        pairs = []
        
        for i in range(len(successful_trajectory.steps) - 1):
            current_step = successful_trajectory.steps[i]
            next_step = successful_trajectory.steps[i+1]
            
            # Current state
            current_state_image = current_step.state_image
            current_state_desc = current_step.state_desc
            
            # Action taken
            action = current_step.action + " " + current_step.object
            
            # Chosen next state (from successful trajectory)
            chosen_next_state = next_step.state_desc
            
            # Get alternative next states from other actions
            state_action_key = (current_state_image, i)
            if state_action_key in all_executed_actions:
                alt_actions = [
                    a for a in all_executed_actions[state_action_key]
                    if a["action"] != action and a["success"]
                ]
                
                for alt_action in alt_actions:
                    rejected_next_state = alt_action["next_state_desc"]
                    
                    pair = StatePreferencePair(
                        current_state_image=current_state_image,
                        current_state_desc=current_state_desc,
                        action=action,
                        chosen_next_state=chosen_next_state,
                        rejected_next_state=rejected_next_state
                    )
                    pairs.append(pair)
        
        return pairs

#################################
# D²PO Model and Training
#################################

class D2POModel(nn.Module):
    def __init__(self, model_name, model_type="vlm"):
        """
        Initialize D²PO model
        
        Args:
            model_name: Name of the base LVLM (Qwen2-VL, LLaVA, etc.)
            model_type: Either "vlm" for vision-language model or "lm" for language model
        """
        super(D2POModel, self).__init__()
        
        self.model_type = model_type
        self.model = AutoModelForCausalLM.from_pretrained(model_name)
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        
    def encode_image(self, image_path):
        """Process image input according to model type"""
        if self.model_type == "vlm":
            # For VLMs, we would use the model's image processor
            # This is simplified as each model has its own way of handling images
            image = Image.open(image_path).convert("RGB")
            # This is a placeholder for the actual image processing
            return self.model.process_image(image)
        else:
            # For LMs, we might use image captions or ignore images
            return None
    
    def forward(self, input_ids, attention_mask, labels=None, images=None):
        """Forward pass for the model"""
        inputs = {
            "input_ids": input_ids,
            "attention_mask": attention_mask,
        }
        
        if images is not None and self.model_type == "vlm":
            inputs["images"] = images
            
        if labels is not None:
            inputs["labels"] = labels
            
        return self.model(**inputs)
    
    def generate_action(self, state_image, state_desc, goal, previous_actions, previous_observations):
        """Generate next action given the current state"""
        # Construct prompt
        prompt = f"Goal: {goal}\n"
        
        for i, (action, obs) in enumerate(zip(previous_actions, previous_observations)):
            prompt += f"Step {i+1}: {action} -> {obs}\n"
            
        prompt += f"Current state: {state_desc}\nGenerate the next action:"
        
        # Tokenize
        inputs = self.tokenizer(prompt, return_tensors="pt").to(self.model.device)
        
        # Add image if VLM
        if self.model_type == "vlm" and state_image is not None:
            image_tensor = self.encode_image(state_image)
            inputs["images"] = image_tensor.to(self.model.device)
        
        # Generate
        output_ids = self.model.generate(
            **inputs,
            max_new_tokens=100,
            temperature=0.8,
            do_sample=True
        )
        
        # Decode
        generated_text = self.tokenizer.decode(output_ids[0], skip_special_tokens=True)
        action_text = generated_text[len(prompt):].strip()
        parts = action_text.split("Action:")
        reasoning = parts[0].replace("Reasoning:", "").strip() if len(parts) > 1 else ""
        action = parts[1].strip() if len(parts) > 1 else action_text
        
        return {
            "action": action,
            "reasoning": reasoning
        }
    
    def predict_next_state(self, state_image, state_desc, action):
        """Predict the next state after taking an action"""
        # Construct prompt
        prompt = f"Current state: {state_desc}\nAction: {action}\nPredict the next state:"
        
        # Tokenize
        inputs = self.tokenizer(prompt, return_tensors="pt").to(self.model.device)
        
        # Add image if VLM
        if self.model_type == "vlm" and state_image is not None:
            image_tensor = self.encode_image(state_image)
            inputs["images"] = image_tensor.to(self.model.device)
        
        # Generate
        output_ids = self.model.generate(
            **inputs,
            max_new_tokens=100,
            temperature=0.2,  # Lower temperature for state prediction
        )
        
        # Decode
        generated_text = self.tokenizer.decode(output_ids[0], skip_special_tokens=True)
        next_state = generated_text[len(prompt):].strip()
        
        return next_state

class ActionPreferenceDataset(Dataset):
    def __init__(self, preference_pairs, tokenizer, max_length=512):
        self.preference_pairs = preference_pairs
        self.tokenizer = tokenizer
        self.max_length = max_length
        
    def __len__(self):
        return len(self.preference_pairs)
    
    def __getitem__(self, idx):
        pair = self.preference_pairs[idx]
        
        # Construct prompt for chosen action
        chosen_prompt = f"Goal: {pair.goal}\n"
        
        for i, (action, obs) in enumerate(zip(pair.prev_actions, pair.prev_observations)):
            chosen_prompt += f"Step {i+1}: {action} -> {obs}\n"
            
        chosen_prompt += f"Reasoning: {pair.chosen_reasoning}\nAction: {pair.chosen_action}"
        
        # Construct prompt for rejected action
        rejected_prompt = f"Goal: {pair.goal}\n"
        
        for i, (action, obs) in enumerate(zip(pair.prev_actions, pair.prev_observations)):
            rejected_prompt += f"Step {i+1}: {action} -> {obs}\n"
            
        rejected_prompt += f"Reasoning: {pair.rejected_reasoning}\nAction: {pair.rejected_action}"
        
        # Tokenize
        chosen_encodings = self.tokenizer(
            chosen_prompt, 
            max_length=self.max_length, 
            padding="max_length", 
            truncation=True,
            return_tensors="pt"
        )
        
        rejected_encodings = self.tokenizer(
            rejected_prompt, 
            max_length=self.max_length, 
            padding="max_length", 
            truncation=True,
            return_tensors="pt"
        )
        
        return {
            "chosen_input_ids": chosen_encodings.input_ids.squeeze(),
            "chosen_attention_mask": chosen_encodings.attention_mask.squeeze(),
            "rejected_input_ids": rejected_encodings.input_ids.squeeze(),
            "rejected_attention_mask": rejected_encodings.attention_mask.squeeze(),
        }

class StatePreferenceDataset(Dataset):
    def __init__(self, preference_pairs, tokenizer, max_length=512):
        self.preference_pairs = preference_pairs
        self.tokenizer = tokenizer
        self.max_length = max_length
        
    def __len__(self):
        return len(self.preference_pairs)
    
    def __getitem__(self, idx):
        pair = self.preference_pairs[idx]
        
        # Construct prompt for chosen state
        chosen_prompt = f"Current state: {pair.current_state_desc}\nAction: {pair.action}\nNext state: {pair.chosen_next_state}"
        
        # Construct prompt for rejected state
        rejected_prompt = f"Current state: {pair.current_state_desc}\nAction: {pair.action}\nNext state: {pair.rejected_next_state}"
        
        # Tokenize
        chosen_encodings = self.tokenizer(
            chosen_prompt, 
            max_length=self.max_length, 
            padding="max_length", 
            truncation=True,
            return_tensors="pt"
        )
        
        rejected_encodings = self.tokenizer(
            rejected_prompt, 
            max_length=self.max_length, 
            padding="max_length", 
            truncation=True,
            return_tensors="pt"
        )
        
        # For Vision-Language Models, we would also process images
        # This is a simplified version without image processing
        
        return {
            "chosen_input_ids": chosen_encodings.input_ids.squeeze(),
            "chosen_attention_mask": chosen_encodings.attention_mask.squeeze(),
            "rejected_input_ids": rejected_encodings.input_ids.squeeze(),
            "rejected_attention_mask": rejected_encodings.attention_mask.squeeze(),
            "image_path": pair.current_state_image,  # For illustration - actual processing depends on the model
        }

class D2POTrainer:
    def __init__(
        self, 
        model, 
        ref_model,
        tokenizer,
        action_preference_pairs,
        state_preference_pairs,
        beta=0.1,
        lambda_weight=1.0,
        lr=5e-7,
        batch_size=32,
        num_epochs=1,
        device="cuda"
    ):
        """
        Initialize the D²PO trainer
        
        Args:
            model: The model to be trained
            ref_model: Reference model (SFT model)
            tokenizer: Tokenizer
            action_preference_pairs: List of action preference pairs
            state_preference_pairs: List of state preference pairs
            beta: DPO beta parameter
            lambda_weight: Weight for state prediction loss
            lr: Learning rate
            batch_size: Batch size
            num_epochs: Number of epochs
            device: Device to train on
        """
        self.model = model.to(device)
        self.ref_model = ref_model.to(device)
        self.tokenizer = tokenizer
        self.beta = beta
        self.lambda_weight = lambda_weight
        self.device = device
        
        # Freeze reference model
        for param in self.ref_model.parameters():
            param.requires_grad = False
            
        # Create datasets
        self.action_dataset = ActionPreferenceDataset(action_preference_pairs, tokenizer)
        self.state_dataset = StatePreferenceDataset(state_preference_pairs, tokenizer)
        
        # Create dataloaders
        self.action_dataloader = DataLoader(
            self.action_dataset, 
            batch_size=batch_size, 
            shuffle=True
        )
        
        self.state_dataloader = DataLoader(
            self.state_dataset, 
            batch_size=batch_size, 
            shuffle=True
        )
        
        # Optimizer
        self.optimizer = optim.Adam(self.model.parameters(), lr=lr)
        
        self.num_epochs = num_epochs
    
    def compute_logps(self, input_ids, attention_mask, images=None):
        """Compute log probabilities for sequences"""
        with torch.no_grad():
            outputs = self.model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                images=images
            )
            
        logits = outputs.logits
        
        # Shift logits and input_ids for next token prediction
        shift_logits = logits[:, :-1, :].contiguous()
        shift_labels = input_ids[:, 1:].contiguous()
        
        # Compute log probs
        log_probs = F.log_softmax(shift_logits, dim=-1)
        token_log_probs = log_probs.gather(-1, shift_labels.unsqueeze(-1)).squeeze(-1)
        
        # Mask padding tokens
        mask = attention_mask[:, 1:].contiguous()
        token_log_probs = token_log_probs * mask
        
        # Sum log probs
        sequence_log_probs = token_log_probs.sum(dim=-1) / mask.sum(dim=-1)
        
        return sequence_log_probs
    
    def dpo_loss(self, chosen_logps, chosen_ref_logps, rejected_logps, rejected_ref_logps):
        """Compute DPO loss"""
        logits = self.beta * (chosen_logps - chosen_ref_logps - (rejected_logps - rejected_ref_logps))
        losses = -F.logsigmoid(logits)
        return losses.mean()
    
    def train_epoch(self, epoch):
        """Train for one epoch"""
        self.model.train()
        total_loss = 0
        action_loss = 0
        state_loss = 0
        
        # Determine number of iterations (max of action and state dataloaders)
        num_batches = max(len(self.action_dataloader), len(self.state_dataloader))
        
        # Create iterators
        action_iter = iter(self.action_dataloader)
        state_iter = iter(self.state_dataloader)
        
        # Track processed data
        action_batches_processed = 0
        state_batches_processed = 0
        
        for i in range(num_batches):
            self.optimizer.zero_grad()
            batch_loss = 0
            
            # Process action batch if available
            if action_batches_processed < len(self.action_dataloader):
                try:
                    action_batch = next(action_iter)
                    action_batches_processed += 1
                    
                    # Move to device
                    chosen_input_ids = action_batch["chosen_input_ids"].to(self.device)
                    chosen_attention_mask = action_batch["chosen_attention_mask"].to(self.device)
                    rejected_input_ids = action_batch["rejected_input_ids"].to(self.device)
                    rejected_attention_mask = action_batch["rejected_attention_mask"].to(self.device)
                    
                    # Compute log probs for model
                    chosen_logps = self.compute_logps(
                        chosen_input_ids, 
                        chosen_attention_mask
                    )
                    
                    rejected_logps = self.compute_logps(
                        rejected_input_ids, 
                        rejected_attention_mask
                    )
                    
                    # Compute log probs for reference model
                    with torch.no_grad():
                        chosen_ref_logps = self.compute_logps(
                            chosen_input_ids, 
                            chosen_attention_mask
                        )
                        
                        rejected_ref_logps = self.compute_logps(
                            rejected_input_ids, 
                            rejected_attention_mask
                        )
                    
                    # Compute action selection loss
                    batch_action_loss = self.dpo_loss(
                        chosen_logps, 
                        chosen_ref_logps, 
                        rejected_logps, 
                        rejected_ref_logps
                    )
                    
                    action_loss += batch_action_loss.item()
                    batch_loss += batch_action_loss
                    
                except StopIteration:
                    pass
            
            # Process state batch if available
            if state_batches_processed < len(self.state_dataloader):
                try:
                    state_batch = next(state_iter)
                    state_batches_processed += 1
                    
                    # Move to device
                    chosen_input_ids = state_batch["chosen_input_ids"].to(self.device)
                    chosen_attention_mask = state_batch["chosen_attention_mask"].to(self.device)
                    rejected_input_ids = state_batch["rejected_input_ids"].to(self.device)
                    rejected_attention_mask = state_batch["rejected_attention_mask"].to(self.device)
                    
                    # For VLMs, we would also process images
                    # This is simplified
                    
                    # Compute log probs for model
                    chosen_logps = self.compute_logps(
                        chosen_input_ids, 
                        chosen_attention_mask
                    )
                    
                    rejected_logps = self.compute_logps(
                        rejected_input_ids, 
                        rejected_attention_mask
                    )
                    
                    # Compute log probs for reference model
                    with torch.no_grad():
                        chosen_ref_logps = self.compute_logps(
                            chosen_input_ids, 
                            chosen_attention_mask
                        )
                        
                        rejected_ref_logps = self.compute_logps(
                            rejected_input_ids, 
                            rejected_attention_mask
                        )
                    
                    # Compute state prediction loss
                    batch_state_loss = self.dpo_loss(
                        chosen_logps, 
                        chosen_ref_logps, 
                        rejected_logps, 
                        rejected_ref_logps
                    )
                    
                    # Apply lambda weight
                    weighted_state_loss = self.lambda_weight * batch_state_loss
                    
                    state_loss += batch_state_loss.item()
                    batch_loss += weighted_state_loss
                    
                except StopIteration:
                    pass
            
            # Backprop combined loss
            if batch_loss > 0:
                batch_loss.backward()
                self.optimizer.step()
                total_loss += batch_loss.item()
            
        # Compute average losses
        avg_total_loss = total_loss / num_batches
        avg_action_loss = action_loss / action_batches_processed if action_batches_processed > 0 else 0
        avg_state_loss = state_loss / state_batches_processed if state_batches_processed > 0 else 0
        
        return avg_total_loss, avg_action_loss, avg_state_loss
    
    def train(self):
        """Train the model for multiple epochs"""
        best_loss = float('inf')
        
        for epoch in range(self.num_epochs):
            avg_loss, action_loss, state_loss = self.train_epoch(epoch)
            
            print(f"Epoch {epoch+1}/{self.num_epochs}, "
                  f"Total Loss: {avg_loss:.4f}, "
                  f"Action Loss: {action_loss:.4f}, "
                  f"State Loss: {state_loss:.4f}")
            
            # Save best model
            if avg_loss < best_loss:
                best_loss = avg_loss
                torch.save(self.model.state_dict(), "best_d2po_model.pt")
                
        print("Training complete!")
